"use client";

import React, { FC } from "react";
import LandingPage from "../components/layouts/LandingPage";
import SnackBar from "../components/common/SnackBar";
import Loader from "../components/common/Loader";
import { useAppSelector } from "../store/hooks";
import Head from "next/head";
import type { Metadata } from "next";
import { Layout } from "../components/common/Layout";

export const metadata: Metadata = {
    title: "Let's Event | Home",
    // description: "Generated by Next.js",
};

const App: FC = () => {
    const acrossApp = useAppSelector((state) => state.acrossApp);

    return (
        <>
            <Layout>
                <Head>
                    <title>Let's Event | Home</title>
                </Head>
                <LandingPage />
                <SnackBar
                    snack={acrossApp.notification.notification}
                    variant={acrossApp.notification.variant}
                    message={acrossApp.notification.message}
                />
                <Loader isLoading={acrossApp.isLoading} />
            </Layout>
        </>
    );
};

export default App;